name: spacescape
description: A 2D top down space shooter.

publish_to: "none"

version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flame: 1.14.0
  flame_audio: 2.1.7
  provider: 6.1.1
  flutter_carousel_slider: 1.1.0
  hive: 2.2.3
  hive_generator: 2.0.1
  path_provider: 2.1.2
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.6
  hive_flutter: 1.1.0
  # flame_noise: 0.1.1

dev_dependencies:
  build_runner: 2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
  fonts:
    - family: BungeeInline
      fonts:
        - asset: assets/fonts/BungeeInline/BungeeInline-Regular.ttf
